### ISSUE TITLE
Akita Devtools Errors 

### ISSUE THREAD

**Issue by aperez36** [salesforce/akita#812]
Hello, I am running into these errors after installing Akita-Devtools. I installed the latest Akita and Akita-Devtools while running the latest version of Angular. Would anyone be able to assist? 

My app module has the following:
```
import { AkitaNgDevtools } from '@datorama/akita-ngdevtools';

@NgModule({
    declarations: [AppComponent],
    imports: [
        environment.production ? [] : AkitaNgDevtools.forRoot()
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

Seems to be complaining all about fesm2015. 
```
Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 79:19-34
Can't import the named export 'APP_INITIALIZER' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 52:14-20
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 41:10-20
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 6:27-41
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 117:10-18
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 22:11-20
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 48:12-21
Can't import the named export 'NgZone' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 26:10-28
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 97:10-28
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 35:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 111:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 16:21-42
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 91:23-44
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 28:22-46
Can't import the named export 'ɵɵngDeclareInjectable' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 105:23-45
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

Error: ./node_modules/@datorama/akita-ngdevtools/fesm2015/datorama-akita-ngdevtools.mjs 99:23-45
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)
```

**Comment by aperez36** [comment]
Now getting this single error:
```
Error: Can't resolve all parameters for AkitaDevtools: (?, ?).
    at getUndecoratedInjectableFactory (core.js:11495:15)
    at injectableDefOrInjectorDefFactory (core.js:11485:16)
    at providerToFactory (core.js:11528:52)
    at providerToRecord (core.js:11515:25)
    at R3Injector.processProvider (core.js:11419:24)
    at core.js:11392:61
    at core.js:4182:76
    at Array.forEach (<anonymous>)
    at deepForEach (core.js:4182:11)
    at _loop (core.js:11392:21)
```

**Comment by NetanelBasal** [comment]
The module is removed in the new version.

**Comment by jongbonga** [comment]
@NetanelBasal I can see the [new implementation](https://opensource.salesforce.com/akita/docs/enhancers/devtools#usage) on the docs but not sure where to place that code. can we have a reference like which file should the snippet go to?

**Comment by NetanelBasal** [comment]
To the app providers

**Comment by jongbonga** [comment]
> To the app providers

can we have a full example, please?

**Comment by NetanelBasal** [comment]
```ts
bootstrapApplication(AppComponent, {
  providers: [provideAkitaDevtools(options)]
});
```

**Comment by NetanelBasal** [comment]
Or with modules - https://github.com/salesforce/akita/blob/master/packages/ng-playground/src/app/app.module.ts#L37

**Comment by jongbonga** [comment]
Thank you
